POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
"login": "3dpiknik@wp.pl",
  "password": "twojastara357",
  "name": "Ola",
  "surname": "Kochanowska"
}

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
"login": "3dpiknik@wp.pl",
  "password": "twojastara357"
}

###
POST http://localhost:8080/api/product/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzZHBpa25pa0B3cC5wbCIsImlhdCI6MTYzMzcwODI1OSwiZXhwIjoxNjQyMzQ4MjU5fQ.m-0aOEOchGTLIAFggyPH1esW_20ZqTj1DoXGKkBAG-o

{
  "title": "Jakaś oferta",
  "description": "jakiś opis oferty",
  "address": "jakiś adres 45"
}

###

GET http://localhost:8080/api/product/all
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzZHBpa25pa0B3cC5wbCIsImlhdCI6MTYzMzcwODI1OSwiZXhwIjoxNjQyMzQ4MjU5fQ.m-0aOEOchGTLIAFggyPH1esW_20ZqTj1DoXGKkBAG-o


###
